server:
  runMode: debug                 # release/debug/test
  name: goProject                # 注册到consul的服务名
  tag:                           # 注意是字符数组形式, 不允许空数据
  ip: 127.0.0.1                  # 服务的IP
  port: 8000                     # 服务的端口
  consulAddr: 127.0.0.1:8500     # consul的地址
  consulToken:                   # consul的token
  interval: 10                   # 健康检查间隔, 单位：秒
  deregister: 1                  # 注销时间, 相当于过期时间, 单位：分钟

mysql:
  host: 127.0.0.1
  port: 3306
  userName: root
  password: root
  dbName: goCode

redis:
  addr: 127.0.0.1:6379
  password:
  db: 0
  PoolSize: 20

zap:
  level: debug                              # 级别
  prefix: "[goCode] "                       # 日志前缀
  format: json                              # 输出格式
  director: log                             # 日志文件夹
  encodeLevel: LowercaseLevelEncoder        # 编码级别
  stacktraceKey: stacktrace                 # 栈名
  maxAge: 30                                # 日志留存时间, 单位：天
  showLine: true                            # 显示行
  logInConsole: true                        # 输出到控制台
